#!/bin/bash
#SBATCH -o out_glac1d_l71C_p2_5_5010_3990.out
#SBATCH -A jalab
#SBATCH -J glac1d_l71C_p2_5_5010_3990
#SBATCH --mem-per-cpu=32gb
#SBATCH --time=0:30:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user=rcreel@ldeo.columbia.edu
 
module load anaconda
source activate gpflow6_0
python ../run_gpr/run_glac1d_l71C_p2_5_5010_3990
