#!/bin/bash
#SBATCH -o out_glac1d_l96C_p3_7_12010_1990.out
#SBATCH -A jalab
#SBATCH -J glac1d_l96C_p3_7_12010_1990
#SBATCH --mem-per-cpu=125gb
#SBATCH --time=3:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user=rcreel@ldeo.columbia.edu
 
source activate gpflow6_0
cd ../run_gpr/
bash run_glac1d_l96C_p3_7_12010_1990.sh
