#!/bin/bash
#SBATCH -o out_d6g_h6g_l71C_p4_8_12010_1990.out
#SBATCH -A jalab
#SBATCH -J d6g_h6g_l71C_p4_8_12010_1990
#SBATCH --mem-per-cpu=125gb
#SBATCH --time=3:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user=rcreel@ldeo.columbia.edu
 
source activate gpflow6_0
cd ../run_gpr/
bash run_d6g_h6g_l71C_p4_8_12010_1990.sh
